"""Initial migration

Revision ID: dc80ed259b9b
Revises: 
Create Date: 2025-12-22 01:04:29.261875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc80ed259b9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status_read', sa.Boolean(), nullable=False),
    sa.Column('status_interesting', sa.Boolean(), nullable=False),
    sa.Column('content_md', sa.String(), nullable=True),
    sa.Column('comments_data', sa.JSON(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_guid'), 'articles', ['guid'], unique=True)
    settings_table = op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###

    # ### Seed default settings ###
    op.bulk_insert(
        settings_table,
        [
            {
                'key': 'sources.habr_python.type',
                'value': 'habr',
                'type': 'string',
                'description': 'Type of the source.',
            },
            {
                'key': 'sources.habr_python.hubs',
                'value': 'python,django,fastapi',
                'type': 'list',
                'description': 'List of hubs to follow.',
            },
            {
                'key': 'sources.habr_rust.type',
                'value': 'habr',
                'type': 'string',
                'description': 'Type of the source.',
            },
            {
                'key': 'sources.habr_rust.hubs',
                'value': 'rust',
                'type': 'list',
                'description': 'List of hubs to follow.',
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_index(op.f('ix_articles_guid'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
